CREATE TABLE `gen_table` (
  `id` varchar(64) NOT NULL COMMENT '编号',
  `table_name` varchar(200) DEFAULT NULL COMMENT '名称',
  `description` varchar(500) DEFAULT NULL COMMENT '描述',
  `class_name` varchar(100) DEFAULT NULL COMMENT '实体类名称',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_date` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_date` datetime DEFAULT NULL COMMENT '更新时间',
  `remarks` varchar(255) DEFAULT NULL COMMENT '备注信息',
  `del_flag` char(1) NOT NULL DEFAULT '0' COMMENT '删除标记（0：正常；1：删除）',
  PRIMARY KEY (`id`),
  KEY `gen_table_name` (`table_name`),
  KEY `gen_table_del_flag` (`del_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='业务表';

CREATE TABLE `gen_table_column` (
  `id` varchar(64) NOT NULL COMMENT '编号',
  `gen_table_id` varchar(64) DEFAULT NULL COMMENT '归属表编号',
  `column_name` varchar(200) DEFAULT NULL COMMENT '名称',
  `description` varchar(500) DEFAULT NULL COMMENT '描述',
  `jdbc_type` varchar(100) DEFAULT NULL COMMENT '列的数据类型的字节长度',
  `java_type` varchar(500) DEFAULT NULL COMMENT 'JAVA类型',
  `java_field` varchar(200) DEFAULT NULL COMMENT 'JAVA字段名',
  `is_pk` char(1) DEFAULT NULL COMMENT '是否主键',
  `is_null` char(1) DEFAULT NULL COMMENT '是否可为空',
  `is_insert` char(1) DEFAULT NULL COMMENT '是否为插入字段',
  `is_edit` char(1) DEFAULT NULL COMMENT '是否编辑字段',
  `is_list` char(1) DEFAULT NULL COMMENT '是否列表字段',
  `is_query` char(1) DEFAULT NULL COMMENT '是否查询字段',
  `query_type` varchar(200) DEFAULT NULL COMMENT '查询方式（等于、不等于、大于、小于、范围、左LIKE、右LIKE、左右LIKE）',
  `show_type` varchar(200) DEFAULT NULL COMMENT '字段生成方案（文本框、文本域、下拉框、复选框、单选框、字典选择、人员选择、部门选择、区域选择）',
  `dict_type` varchar(200) DEFAULT NULL COMMENT '字典类型',
  `settings` varchar(2000) DEFAULT NULL COMMENT '其它设置（扩展字段JSON）',
  `sort` decimal(10,0) DEFAULT NULL COMMENT '排序（升序）',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_date` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_date` datetime DEFAULT NULL COMMENT '更新时间',
  `remarks` varchar(255) DEFAULT NULL COMMENT '备注信息',
  `del_flag` char(1) NOT NULL DEFAULT '0' COMMENT '删除标记（0：正常；1：删除）',
  PRIMARY KEY (`id`),
  KEY `gen_table_column_table_id` (`gen_table_id`),
  KEY `gen_table_column_name` (`column_name`),
  KEY `gen_table_column_sort` (`sort`),
  KEY `gen_table_column_del_flag` (`del_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='业务表字段';

CREATE TABLE `sys_dict` (
  `id` varchar(64) NOT NULL COMMENT '编号',
  `value` varchar(100) NOT NULL COMMENT '数据值',
  `label` varchar(100) NOT NULL COMMENT '标签名',
  `type` varchar(100) NOT NULL COMMENT '类型',
  `description` varchar(100) NOT NULL COMMENT '描述',
  `sort` decimal(10,0) NOT NULL COMMENT '排序（升序）',
  `create_by` varchar(64) NOT NULL COMMENT '创建者',
  `create_date` datetime NOT NULL COMMENT '创建时间',
  `update_by` varchar(64) NOT NULL COMMENT '更新者',
  `update_date` datetime NOT NULL COMMENT '更新时间',
  `remarks` varchar(255) DEFAULT NULL COMMENT '备注信息',
  `del_flag` char(1) NOT NULL DEFAULT '0' COMMENT '删除标记',
  PRIMARY KEY (`id`),
  KEY `sys_dict_value` (`value`),
  KEY `sys_dict_label` (`label`),
  KEY `sys_dict_del_flag` (`del_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='字典表';

CREATE TABLE `sys_menu` (
  `id` varchar(60) NOT NULL COMMENT 'ID',
  `parent_id` varchar(60) DEFAULT NULL COMMENT '所有父级菜单ID',
  `parent_ids` varchar(1000) DEFAULT NULL COMMENT '所有父级菜单ID集合',
  `name` varchar(255) DEFAULT NULL COMMENT '菜单名称',
  `href` varchar(255) DEFAULT NULL COMMENT '连接地址',
  `permission` varchar(255) DEFAULT NULL COMMENT '权限',
  `icon` varchar(60) DEFAULT NULL COMMENT '图标',
  `is_show` varchar(1) DEFAULT NULL COMMENT '是否显示',
  `sort` int(255) DEFAULT NULL COMMENT '排序',
  `level` varchar(60) DEFAULT NULL COMMENT '等级(深度)',
  `history` varchar(2000) DEFAULT NULL COMMENT '历史记录',
  `remarks` varchar(255) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(60) DEFAULT NULL COMMENT '创建者',
  `update_by` varchar(60) DEFAULT NULL COMMENT '更新着',
  `create_date` datetime DEFAULT NULL COMMENT '创建时间',
  `update_date` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` varchar(1) DEFAULT NULL COMMENT '删除标记（0：正常；1：删除；2：审核）',
  PRIMARY KEY (`id`),
  KEY `id` (`id`) USING BTREE,
  KEY `parent_id` (`parent_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='系统菜单表';

CREATE TABLE `sys_user` (
  `id` varchar(64) NOT NULL COMMENT 'ID',
  `nickname` varchar(255) DEFAULT NULL COMMENT '系统昵称',
  `username` varchar(255) DEFAULT NULL COMMENT '用户名',
  `password` varchar(255) DEFAULT NULL COMMENT '密码',
  `email` varchar(255) DEFAULT NULL COMMENT '邮箱',
  `id_card` varchar(255) DEFAULT NULL COMMENT '身份证',
  `sex` varchar(10) DEFAULT NULL COMMENT '性别',
  `mobile_number` varchar(255) DEFAULT NULL COMMENT '手机号',
  `telephone` varchar(255) DEFAULT NULL COMMENT '手机号',
  `status` varchar(255) DEFAULT NULL COMMENT '用户状态',
  `number` varchar(255) DEFAULT NULL COMMENT '编号',
  `user_type` varchar(255) DEFAULT NULL COMMENT '用户类型',
  `last_login_ip` varchar(255) DEFAULT NULL COMMENT '上次登录IP',
  `last_login_date` datetime DEFAULT NULL COMMENT '上次登录日期',
  `regis_time` datetime DEFAULT NULL COMMENT '注册时间',
  `regis_place` varchar(255) DEFAULT NULL COMMENT '注册地点',
  `history` varchar(2000) DEFAULT NULL COMMENT '历史记录',
  `remarks` varchar(255) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(60) DEFAULT NULL COMMENT '创建者',
  `update_by` varchar(60) DEFAULT NULL COMMENT '更新着',
  `create_date` datetime DEFAULT NULL COMMENT '创建时间',
  `update_date` datetime DEFAULT NULL COMMENT '更新时间',
  `del_flag` varchar(1) DEFAULT NULL COMMENT '删除标记（0：正常；1：删除；2：审核）',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



